version: "3.8"
services:
  web:
    image: php:8.1-apache
    container_name: smartdev_web
    ports:
      - "8089:80"
    volumes:
      - ./:/var/www/html:cached
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    restart: unless-stopped
